export type AssetRole =
  | 'hero-atmosphere'
  | 'dossier-portrait'
  | 'card-art'
  | 'background-wash'
  | 'watermark'
  | 'section-divider'
  | 'hover-ornament'
  | 'button-ornament'
  | 'seal-stamp'
  | 'texture'
  | 'unusable'

export type SectionFit =
  | 'home' | 'characters' | 'world' | 'cultivation' | 'swordsmanship'
  | 'factions' | 'artifacts' | 'timeline' | 'rankings' | 'teachings'
  | 'glossary' | 'pantheon' | 'global'

export type Mood =
  | 'solemn' | 'misty' | 'celestial' | 'martial' | 'pastoral'
  | 'arcane' | 'elegiac' | 'burnished'

export type CropType =
  | 'subject-up' | 'eyes-up' | 'center' | 'lower-third'
  | 'left-third' | 'right-third' | 'full-bleed'

export interface AssetEntry {
  id: string
  filePath: string
  role: AssetRole
  sectionFit: SectionFit[]
  mood: Mood
  subject: string
  aspectRatio: string
  cropType: CropType
  recommendedUse: string
  avoidUse: string
  priority: 'p0' | 'p1' | 'p2' | 'p3'
  curatedAt: string
  curatedBy: string
  notes?: string
}

export interface AssetManifest {
  version: string
  assets: AssetEntry[]
}

const manifest: AssetManifest = {
  version: '1.0.0',
  assets: [
    {
      id: 'asset.char-chen-pingan-portrait',
      filePath: '/images/characters/chen-pingan.webp',
      role: 'dossier-portrait',
      sectionFit: ['characters'],
      mood: 'solemn',
      subject: 'Chen Ping\'an in scholar robes',
      aspectRatio: '3:4',
      cropType: 'eyes-up',
      recommendedUse: 'Dossier plate on /characters/chen-pingan',
      avoidUse: 'Hero atmosphere (too tight a crop)',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
      notes: 'Primary character portrait, high resolution',
    },
    {
      id: 'asset.char-ning-yao-portrait',
      filePath: '/images/characters/ning-yao.webp',
      role: 'dossier-portrait',
      sectionFit: ['characters'],
      mood: 'elegiac',
      subject: 'Ning Yao portrait',
      aspectRatio: '3:4',
      cropType: 'eyes-up',
      recommendedUse: 'Dossier plate on /characters/ning-yao',
      avoidUse: 'Card art (wrong aspect ratio)',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.char-qi-jingchun-portrait',
      filePath: '/images/characters/qi-jingchun.webp',
      role: 'dossier-portrait',
      sectionFit: ['characters'],
      mood: 'martial',
      subject: 'Qi Jingchun portrait',
      aspectRatio: '3:4',
      cropType: 'eyes-up',
      recommendedUse: 'Dossier plate on /characters/qi-jingchun',
      avoidUse: 'Card art',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.banner-characters-hero',
      filePath: '/images/banners/characters-banner.webp',
      role: 'hero-atmosphere',
      sectionFit: ['characters'],
      mood: 'misty',
      subject: 'Characters section hero atmosphere',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Section hero background wash on /characters',
      avoidUse: 'Card art or portrait overlay',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.banner-swordsmanship-hero',
      filePath: '/images/banners/swordsmanship-banner.webp',
      role: 'hero-atmosphere',
      sectionFit: ['swordsmanship'],
      mood: 'martial',
      subject: 'Swordsmanship section hero atmosphere',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Section hero background wash on /swordsmanship',
      avoidUse: 'Card art',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.banner-world-hero',
      filePath: '/images/banners/world-banner.webp',
      role: 'hero-atmosphere',
      sectionFit: ['world'],
      mood: 'celestial',
      subject: 'World section hero atmosphere',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Section hero background wash on /world',
      avoidUse: 'Card art',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.banner-cultivation-hero',
      filePath: '/images/banners/cultivation-banner.webp',
      role: 'hero-atmosphere',
      sectionFit: ['cultivation'],
      mood: 'arcane',
      subject: 'Cultivation section hero atmosphere',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Section hero background wash on /cultivation',
      avoidUse: 'Card art',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.banner-factions-hero',
      filePath: '/images/banners/factions-banner.webp',
      role: 'hero-atmosphere',
      sectionFit: ['factions'],
      mood: 'burnished',
      subject: 'Factions section hero atmosphere',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Section hero background wash on /factions',
      avoidUse: 'Card art',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.banner-artifacts-hero',
      filePath: '/images/banners/artifacts-banner.webp',
      role: 'hero-atmosphere',
      sectionFit: ['artifacts'],
      mood: 'burnished',
      subject: 'Artifacts section hero atmosphere',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Section hero background wash on /artifacts',
      avoidUse: 'Card art',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.banner-home-hero',
      filePath: '/images/banners/home-hero.webp',
      role: 'hero-atmosphere',
      sectionFit: ['home'],
      mood: 'solemn',
      subject: 'Home page hero atmosphere',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Home page hero background wash',
      avoidUse: 'Card art',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.card-char-portal',
      filePath: '/images/portalcard/Character-portalcard.webp',
      role: 'card-art',
      sectionFit: ['characters'],
      mood: 'misty',
      subject: 'Character portal card illustration',
      aspectRatio: '4:5',
      cropType: 'subject-up',
      recommendedUse: 'Card art for FeaturedDossier or character card heroes',
      avoidUse: 'Dossier portrait (wrong role)',
      priority: 'p1',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.card-artifacts-portal',
      filePath: '/images/portalcard/artifacts-portalcard.jpg',
      role: 'card-art',
      sectionFit: ['artifacts'],
      mood: 'burnished',
      subject: 'Artifacts portal card illustration',
      aspectRatio: '4:5',
      cropType: 'subject-up',
      recommendedUse: 'Card art for RelicCard in Artifacts section',
      avoidUse: 'Hero atmosphere',
      priority: 'p1',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.card-cultivation-portal',
      filePath: '/images/portalcard/cultivation-portalcard.jpg',
      role: 'card-art',
      sectionFit: ['cultivation'],
      mood: 'arcane',
      subject: 'Cultivation portal card illustration',
      aspectRatio: '4:5',
      cropType: 'subject-up',
      recommendedUse: 'Card art for cultivation-related entries',
      avoidUse: 'Hero atmosphere',
      priority: 'p1',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.timeline-chen-pingan-art',
      filePath: '/images/timeline/chen-pingan-black-gold-timeline.webp',
      role: 'card-art',
      sectionFit: ['timeline', 'characters'],
      mood: 'martial',
      subject: 'Chen Ping\'an timeline illustration in black and gold',
      aspectRatio: '16:9',
      cropType: 'center',
      recommendedUse: 'Timeline event illustration or card art',
      avoidUse: 'Portrait (too wide)',
      priority: 'p1',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.texture-ink-wash-01',
      filePath: '/images/textures/ink-wash-01.webp',
      role: 'texture',
      sectionFit: ['global'],
      mood: 'misty',
      subject: 'Ink wash texture 01 — atmospheric paper grain',
      aspectRatio: '1:1',
      cropType: 'full-bleed',
      recommendedUse: 'Section hero atmospheric wash at 0.04–0.08 opacity',
      avoidUse: 'Card background or hero at full opacity',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.texture-ink-wash-02',
      filePath: '/images/textures/ink-wash-02.webp',
      role: 'texture',
      sectionFit: ['global'],
      mood: 'misty',
      subject: 'Ink wash texture 02 — atmospheric paper grain variant',
      aspectRatio: '1:1',
      cropType: 'full-bleed',
      recommendedUse: 'Section hero atmospheric wash at 0.04–0.08 opacity',
      avoidUse: 'Card background or hero at full opacity',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
    },
    {
      id: 'asset.seal-border-mask',
      filePath: '/images/ui/seals/seal-border-mask.svg',
      role: 'seal-stamp',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Seal border irregular edge mask for cinnabar stamps',
      aspectRatio: '1:1',
      cropType: 'center',
      recommendedUse: 'Mask for SealButton and SealStamp irregular edges',
      avoidUse: 'As a standalone image',
      priority: 'p0',
      curatedAt: '2025-01-01',
      curatedBy: 'curator',
      notes: 'SVG mask used via CSS mask-image',
    },

    // ── Stage 35D-1B: UI texture assets ───────────────────────────────

    // Cleaned hover brush marks (α-preserved, matte removed)
    {
      id: 'asset.ui.hover.brush.soft-01',
      filePath: '/images/ui/generated/hover-marks/generated-hover-brush-soft-01.webp',
      role: 'hover-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Soft ink brush hover mark 01 — horizontal brush swipe',
      aspectRatio: '2:1',
      cropType: 'full-bleed',
      recommendedUse: '::before hover wash for InkTextButton / InkHoverLink / InkActiveTab; opacity fade 0→0.85, 220–280ms',
      avoidUse: 'Dark background without de-matte verification; vertical stretch',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Clean alpha confirmed 35D-1A. Replace hard-coded ref in SwordArtRegister.vue:279.',
    },
    {
      id: 'asset.ui.hover.brush.soft-02',
      filePath: '/images/ui/generated/hover-marks/generated-hover-brush-soft-02.webp',
      role: 'hover-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Soft ink brush hover mark 02 — currently bound to --jl-hover-brush',
      aspectRatio: '2:1',
      cropType: 'full-bleed',
      recommendedUse: 'Global hover wash bound to --jl-hover-brush; consume via BrushUnderline / InkButton / InkTextButton',
      avoidUse: 'Dark background without de-matte verification',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Most-wired brush mark (4 Vue components). Clean alpha confirmed 35D-1A.',
    },
    {
      id: 'asset.ui.hover.brush.soft-03',
      filePath: '/images/ui/generated/hover-marks/generated-hover-brush-soft-03.webp',
      role: 'hover-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Soft ink brush hover mark 03 — denser variant',
      aspectRatio: '2:1',
      cropType: 'full-bleed',
      recommendedUse: 'Alternative hover brush for denser sections; opacity fade only',
      avoidUse: 'Dark background without de-matte verification',
      priority: 'p1',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Salvage candidate. Clean alpha confirmed 35D-1A.',
    },
    {
      id: 'asset.ui.hover.brush.soft-04',
      filePath: '/images/ui/generated/hover-marks/generated-hover-brush-soft-04.webp',
      role: 'hover-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Soft ink brush hover mark 04 — densest variant, strongest silhouette',
      aspectRatio: '5:2',
      cropType: 'full-bleed',
      recommendedUse: 'Heavy hover brush for martial/burnished sections; opacity fade only',
      avoidUse: 'Dark background without de-matte verification',
      priority: 'p1',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Salvage candidate. Strongest silhouette among brush marks.',
    },

    // Cleaned underline marks
    {
      id: 'asset.ui.underline.ink.thin-03',
      filePath: '/images/ui/generated/hover-marks/generated-underline-ink-thin-03.webp',
      role: 'hover-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Ink underline mark 03 — currently bound to --jl-active-underline',
      aspectRatio: '8:1',
      cropType: 'full-bleed',
      recommendedUse: 'Active underline for BrushUnderline / InkButton / InkHoverLink / InkActiveTab / InkDivider; scaleX reveal at 0.64rem height',
      avoidUse: 'Vertical stretch (scaleX only); dark background without de-matte verification',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Most-wired UI texture asset (6 Vue components). Clean alpha confirmed 35D-1A.',
    },
    {
      id: 'asset.ui.underline.ink.thin-04',
      filePath: '/images/ui/generated/hover-marks/generated-underline-ink-thin-04.webp',
      role: 'hover-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Ink underline mark 04 — thinner variant',
      aspectRatio: '9:1',
      cropType: 'full-bleed',
      recommendedUse: 'Lighter active underline variant; scaleX reveal only',
      avoidUse: 'Vertical stretch; dark background without de-matte verification',
      priority: 'p1',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Hard-coded in SwordArtRegister.vue:228. Clean alpha confirmed 35D-1A.',
    },

    // Cleaned active rings
    {
      id: 'asset.ui.active.ring.gray-01',
      filePath: '/images/ui/generated/hover-marks/generated-active-ring-gray-01.webp',
      role: 'button-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Gray ink active ring 01 — currently bound to --jl-active-ring',
      aspectRatio: '1:1',
      cropType: 'center',
      recommendedUse: 'Active ring mark for InkTextButton mark-ring; section-tinted via CSS filter:hue-rotate; opacity fade + scale settle',
      avoidUse: 'As a seal-stamp (use cinnabar rings instead); dark background without de-matte verification',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Clean alpha confirmed 35D-1A. Hue-rotate tint for per-section accent.',
    },
    {
      id: 'asset.ui.active.ring.black-01',
      filePath: '/images/ui/generated/hover-marks/generated-active-ring-black-01.webp',
      role: 'button-ornament',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Black ink active ring 01 — strongest ring silhouette',
      aspectRatio: '1:1',
      cropType: 'center',
      recommendedUse: 'Active ring for darker sections or military/martial accents; opacity fade + scale settle',
      avoidUse: 'Dark background without de-matte verification',
      priority: 'p1',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-1A de-matte pipeline',
      notes: 'Salvage candidate. Clean alpha confirmed 35D-1A.',
    },

    // Cinnabar seal marks (already clean, no de-matte needed)
    {
      id: 'asset.ui.active.seal.cinnabar-01',
      filePath: '/images/ui/generated/hover-marks/generated-active-seal-cinnabar-01.webp',
      role: 'seal-stamp',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Cinnabar active seal mark 01 — bold stamp',
      aspectRatio: '1:1',
      cropType: 'center',
      recommendedUse: 'Active seal accent for InkTextButton mark-seal / InkHoverLink mark-seal / PaperSlipCard has-seal; opacity fade + slight scale/rotate',
      avoidUse: 'Dark background — colored fringe is ink-safe but verify',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — original generation pass',
      notes: 'Production-ready per 35D-0 audit. Cinnabar-tinted fringe composites cleanly on all surfaces.',
    },
    {
      id: 'asset.ui.active.seal.cinnabar-02',
      filePath: '/images/ui/generated/hover-marks/generated-active-seal-cinnabar-02.webp',
      role: 'seal-stamp',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Cinnabar active seal mark 02 — currently bound to --jl-active-seal',
      aspectRatio: '1:1',
      cropType: 'center',
      recommendedUse: 'Primary active seal, bound to --jl-active-seal; consume via InkTextButton / InkHoverLink / InkActiveTab / PaperSlipCard',
      avoidUse: 'Dark background — colored fringe is ink-safe but verify',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — original generation pass',
      notes: 'Production-ready per 35D-0 audit. Already consumed by 4 primitives.',
    },
    {
      id: 'asset.ui.active.seal.cinnabar-03',
      filePath: '/images/ui/generated/hover-marks/generated-active-seal-cinnabar-03.webp',
      role: 'seal-stamp',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Cinnabar active seal mark 03 — quietest variant',
      aspectRatio: '1:1',
      cropType: 'center',
      recommendedUse: 'Muted seal accent for dense UI, ArchiveTab active marker; opacity fade + slight scale/rotate',
      avoidUse: 'Dark background — colored fringe is ink-safe but verify',
      priority: 'p1',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — original generation pass',
      notes: 'Production-ready per 35D-0 audit. Quietest for dense layouts.',
    },
    {
      id: 'asset.ui.active.ring.cinnabar-01',
      filePath: '/images/ui/generated/hover-marks/generated-active-ring-cinnabar-01.webp',
      role: 'seal-stamp',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Cinnabar active ring 01 — ideal for seal-flavored active states',
      aspectRatio: '1:1',
      cropType: 'center',
      recommendedUse: 'Cinnabar-tinted active ring for seal-flavored active states; opacity fade + scale settle',
      avoidUse: 'Dark background — colored fringe is ink-safe but verify',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — original generation pass',
      notes: 'Only clean ring in the generated pool per 35D-0. Replacement candidate for gray ring on dark surfaces.',
    },

    // Swordsmanship-v2 slash dividers (clean alpha)
    {
      id: 'asset.swordsmanship.divider.slash-01',
      filePath: '/images/ui/generated/swordsmanship-v2/swordsmanship-divider-slash-01.webp',
      role: 'section-divider',
      sectionFit: ['swordsmanship'],
      mood: 'martial',
      subject: 'Blade slash divider 01 — wide steel-blue diagonal',
      aspectRatio: '18:1',
      cropType: 'full-bleed',
      recommendedUse: 'SectionDivider motif=blade for swordsmanship section; scaleX blade-line draw reveal',
      avoidUse: 'Non-swordsmanship sections (wrong mood); opacity fade (use scaleX)',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — swordsmanship-v2 generation pass',
      notes: 'Clean steel-blue fringe. Glow-on-dark is intended blade light, not matte. Production-ready.',
    },
    {
      id: 'asset.swordsmanship.divider.slash-02',
      filePath: '/images/ui/generated/swordsmanship-v2/swordsmanship-divider-slash-02.webp',
      role: 'section-divider',
      sectionFit: ['swordsmanship'],
      mood: 'martial',
      subject: 'Blade slash divider 02 — lighter, thinner stroke',
      aspectRatio: '25:1',
      cropType: 'full-bleed',
      recommendedUse: 'Alternative blade divider for sub-sections; scaleX blade-line draw reveal',
      avoidUse: 'Non-swordsmanship sections; opacity fade',
      priority: 'p1',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — swordsmanship-v2 generation pass',
      notes: 'Clean steel-blue fringe. Production-ready.',
    },
    {
      id: 'asset.swordsmanship.divider.slash-03',
      filePath: '/images/ui/generated/swordsmanship-v2/swordsmanship-divider-slash-03.webp',
      role: 'section-divider',
      sectionFit: ['swordsmanship'],
      mood: 'martial',
      subject: 'Blade slash divider 03 — sharpest, narrowest variant',
      aspectRatio: '27:1',
      cropType: 'full-bleed',
      recommendedUse: 'Sharp blade divider for technique subsections; scaleX blade-line draw reveal',
      avoidUse: 'Non-swordsmanship sections; opacity fade',
      priority: 'p1',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — swordsmanship-v2 generation pass',
      notes: 'Clean steel-blue fringe. Production-ready.',
    },

    // Swordsmanship-v2 slip art + atmosphere
    {
      id: 'asset.swordsmanship.slip.caged-sparrow',
      filePath: '/images/ui/generated/swordsmanship-v2/swordsmanship-caged-sparrow-slip-art-960.webp',
      role: 'card-art',
      sectionFit: ['swordsmanship'],
      mood: 'pastoral',
      subject: 'Caged Sparrow swordsmanship slip art — ink-and-wash illustration',
      aspectRatio: '4:5',
      cropType: 'subject-up',
      recommendedUse: 'ManualSlip hero illustration for swordsmanship Caged Sparrow technique detail; slow fade-in on enter, no hover',
      avoidUse: 'Hero atmosphere (too detailed, use mist-bg instead); transparent overlay',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — swordsmanship-v2 generation pass',
      notes: 'Opaque image, cropped not matted. Production-ready.',
    },
    {
      id: 'asset.swordsmanship.hero.mist-bg',
      filePath: '/images/ui/generated/swordsmanship-v2/swordsmanship-hero-mist-bg.webp',
      role: 'hero-atmosphere',
      sectionFit: ['swordsmanship'],
      mood: 'martial',
      subject: 'Swordsmanship hero mist background wash',
      aspectRatio: '2:1',
      cropType: 'full-bleed',
      recommendedUse: 'SwordDaoManualHero atmosphere wash; static or slow fade-in, no hover (DESIGN §5.1.1)',
      avoidUse: 'As a standalone illustration (use slip-art instead); interactive hover',
      priority: 'p0',
      curatedAt: '2025-06-24',
      curatedBy: 'Stage 35D-0 audit — swordsmanship-v2 generation pass',
      notes: 'Opaque atmosphere wash. Not an alpha asset. Production-ready.',
    },

    // ── Stage 35D-1H: Purchased CSS texture assets ──────────────────

    // Purchased ink — title brush (consumed via --jl-title-brush)
    {
      id: 'asset.ui.purchased.ink.title-stroke-long-06',
      filePath: '/images/ui/purchased/ink/ink-title-stroke-long-06.webp',
      role: 'section-divider',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Purchased ink title brush stroke — long horizontal ink wash',
      aspectRatio: '3:1',
      cropType: 'full-bleed',
      recommendedUse: 'BrushTitle and SectionDivider motif="ink"; scaleX reveal; section header ornament',
      avoidUse: 'Small buttons, active states, repeated tiled backgrounds',
      priority: 'p0',
      curatedAt: '2025-06-25',
      curatedBy: 'Stage 35D-1H — purchased asset registration',
      notes: 'Purchased ink asset. Clean alpha — ink-colored fringe. Production-ready. Consumed via --jl-title-brush CSS variable.',
    },
    // Purchased ink — divider (consumed via --jl-divider-ink)
    {
      id: 'asset.ui.purchased.ink.divider-thin-01',
      filePath: '/images/ui/purchased/ink/ink-divider-thin-01.webp',
      role: 'section-divider',
      sectionFit: ['global'],
      mood: 'burnished',
      subject: 'Purchased ink divider stroke — thin horizontal ink line',
      aspectRatio: '3:1',
      cropType: 'full-bleed',
      recommendedUse: 'InkDivider and quiet section separation; scaleX reveal',
      avoidUse: 'Hover states, badges, seals, small icons',
      priority: 'p0',
      curatedAt: '2025-06-25',
      curatedBy: 'Stage 35D-1H — purchased asset registration',
      notes: 'Purchased ink asset. Clean alpha — ink-colored fringe. Production-ready. Consumed via --jl-divider-ink CSS variable.',
    },
  ],
}

export const ASSET_COUNT = manifest.assets.length

export function getAssetsByRole(role: AssetRole): AssetEntry[] {
  return manifest.assets.filter((a) => a.role === role)
}

export function getAssetsBySection(section: SectionFit): AssetEntry[] {
  return manifest.assets.filter((a) => a.sectionFit.includes(section) || a.sectionFit.includes('global'))
}

export function getAssetsByRoleAndSection(role: AssetRole, section: SectionFit): AssetEntry[] {
  return manifest.assets.filter(
    (a) => a.role === role && (a.sectionFit.includes(section) || a.sectionFit.includes('global'))
  )
}

export function getAssetById(id: string): AssetEntry | undefined {
  return manifest.assets.find((a) => a.id === id)
}
